(()=>{
  const $=id=>document.getElementById(id); let installed=false,closing=false;
  const css=`#hintPanel{position:relative!important;display:block!important;grid-template-columns:1fr!important;padding:14px 10px 10px!important;background:linear-gradient(180deg,#fff8e8,#fff1cf)!important;border:1px solid #e2bf78!important;border-radius:14px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.75)!important}#hintPanel[hidden]{display:none!important}#hintPanel .hintArtWrap,#hintPanel .storyTop,#hintPanel #visual,#hintPanel #timesBtn{display:none!important}#hintPanel .hintCopy{display:block!important}#hintCloseX{position:absolute;top:6px;right:7px;width:34px;height:34px;border:0;border-radius:50%;background:#fff9ed;color:#5a402a;box-shadow:0 2px 8px rgba(79,52,24,.14);font:900 24px/30px system-ui;display:flex;align-items:center;justify-content:center;z-index:2;cursor:pointer}#timesTable{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important;padding:0!important;margin:0!important;background:transparent!important;border:0!important}#timesTable[hidden]{display:grid!important}#timesTable:before{content:attr(data-title);grid-column:1/-1;display:block;text-align:center;font:950 16px/1.2 system-ui;color:#5c3d28;margin:0 34px 2px;padding:4px 8px}#timesTable .timesFact{display:flex!important;align-items:center!important;justify-content:center!important;min-height:36px!important;padding:6px 8px!important;border:1px solid #dfc18a!important;border-bottom-width:3px!important;border-radius:10px!important;background:linear-gradient(#fffdf7,#f7e9cc)!important;color:#513823!important;font:900 16px/1 system-ui!important;box-sizing:border-box!important}#timesTable .timesFact.hit{background:linear-gradient(#fff0a8,#ffd65a)!important;border-color:#d79a24!important;color:#402b18!important;box-shadow:0 0 0 2px rgba(255,213,74,.26)!important}#timesTable .timesFact.hit:before{content:'🐾';margin-right:6px;font-size:14px}#hint.hintToggleOn{background:#6b8f3e!important;color:#fff!important}@media(max-width:430px){#hintPanel{padding:12px 8px 8px!important}#hintCloseX{top:5px;right:5px;width:32px;height:32px;font-size:22px}#timesTable{gap:5px!important}#timesTable .timesFact{min-height:34px!important;font-size:14px!important;padding:5px 6px!important}#timesTable:before{font-size:15px!important}}`;
  function lang(){return document.querySelector('.langBtn.active')?.dataset.lang==='en'?'en':'ru'}
  function getNumbers(){const q=($('question')?.textContent||'').match(/\d+/g)?.map(Number)||[];let d=q[0]||Number(($('divisor')?.textContent||'').replace(/\D/g,''))||1,current=q[1]||0;return {d,current:current||d}}
  function solvedCount(){const locks=$('locks')||document.querySelector('.locks');if(!locks)return 0;return locks.querySelectorAll('.lock.open').length}
  function sync(panel,btn,d){const opened=!panel.hidden;btn.classList.toggle('hintToggleOn',opened);btn.setAttribute('aria-expanded',String(opened));btn.textContent=lang()==='ru'?`🐾 Таблица × ${d}`:`🐾 Table × ${d}`}
  function render(){const panel=$('hintPanel'),box=$('timesTable'),btn=$('hint');if(!panel||!box||!btn)return;const {d,current}=getNumbers(),hit=Math.max(1,Math.min(10,Math.floor(current/d)||1)),highlight=solvedCount()<3;box.hidden=false;box.dataset.title=lang()==='ru'?`🐾 Таблица на ${d}`:`🐾 ${d} times table`;box.innerHTML='';for(let i=1;i<=10;i++){const el=document.createElement('div');el.className='timesFact'+(highlight&&i===hit?' hit':'');el.textContent=`${d} × ${i} = ${d*i}`;box.appendChild(el)}sync(panel,btn,d)}
  function closeViaToggle(panel,btn){if(closing)return;closing=true;if(!panel.hidden)btn.click();panel.hidden=true;btn.classList.remove('hintToggleOn');btn.setAttribute('aria-expanded','false');requestAnimationFrame(()=>{panel.hidden=true;render();closing=false})}
  function install(){if(installed)return;const panel=$('hintPanel'),btn=$('hint');if(!panel||!btn)return;installed=true;const st=document.createElement('style');st.id='hint-ui-v1-style';st.textContent=css;document.head.appendChild(st);if(!$('hintCloseX')){const x=document.createElement('button');x.id='hintCloseX';x.type='button';x.textContent='×';x.onclick=e=>{e.preventDefault();e.stopPropagation();closeViaToggle(panel,btn)};panel.appendChild(x)}const oldTimes=$('timesBtn');if(oldTimes)oldTimes.tabIndex=-1;btn.addEventListener('click',()=>requestAnimationFrame(render));new MutationObserver(()=>requestAnimationFrame(render)).observe(panel,{attributes:true,attributeFilter:['hidden']});const question=$('question');if(question)new MutationObserver(()=>requestAnimationFrame(render)).observe(question,{childList:true,subtree:true,characterData:true});const locks=$('locks')||document.querySelector('.locks');if(locks)new MutationObserver(()=>requestAnimationFrame(render)).observe(locks,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});document.querySelectorAll('.langBtn').forEach(b=>b.addEventListener('click',()=>requestAnimationFrame(render)));render()}
  document.addEventListener('DOMContentLoaded',install);
})();