(()=>{
const A='savekitty_analytics_v1',CH='savekitty_challenge_v1',SITE='https://spasipushka.ru/';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const css=`.pk3{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff3d3;color:#4a3424}.pk3 h3{margin:0 0 4px;text-align:center;font:950 17px/1.2 system-ui}.pk3 p{margin:0 0 9px;text-align:center;font:750 12px/1.35 system-ui;color:#765c43}.pk3row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pk3 button{border:0;border-radius:12px;min-height:47px;color:white;font:900 14px system-ui}.pk3 .tg{background:#229ed9}.pk3 .mx{background:#111}.pkcmp{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff8e7;color:#4a3424}.pkcmp h3{text-align:center;margin:0 0 9px;font:950 16px system-ui}.pkcmpg{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pkcmpc{padding:9px;border:1px solid #ead3a6;border-radius:12px;background:#fffdf8;text-align:center}.pkcmpn{font:800 11px system-ui;color:#80664c}.pkcmpt{font:950 24px system-ui;margin-top:3px}.pkcmpr{margin-top:9px;padding:9px;border-radius:11px;background:#ffd45f;text-align:center;font:950 14px system-ui}.pkbadge{display:none;margin:8px auto;width:min(520px,calc(100% - 12px));padding:9px 12px;box-sizing:border-box;border:1px solid #d5ad62;border-radius:13px;background:#fff3cf;color:#4b3523;text-align:center;font:850 12px/1.35 system-ui}`;
function rows(){try{return JSON.parse(localStorage.getItem(A)||'[]')||[]}catch(e){return[]}}
function run(){let a=rows();for(let i=a.length-1;i>=0;i--)if(a[i]&&(a[i].completed===true||a[i].event==='completed'))return a[i];return null}
function sec(r){return Math.max(0,Math.round(Number(r?.duration_seconds??r?.duration_sec??r?.elapsed_sec)||0))}
function nm(r){return String(r?.player_name??r?.name??'Игрок').trim().slice(0,40)||'Игрок'}
function lng(r){return (r?.language??r?.lang)==='en'?'en':'ru'}
function fmt(n){n=Math.max(0,Math.round(+n||0));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
function enc(o){try{return encodeURIComponent(JSON.stringify(o))}catch(e){return''}}
function dec(s){try{return JSON.parse(decodeURIComponent(s))}catch(e){return null}}
function ingest(){let raw=new URLSearchParams(location.search).get('c');if(!raw)return;let c=dec(raw);if(c&&+c.t>0)try{sessionStorage.setItem(CH,JSON.stringify({n:String(c.n||'Друг').slice(0,40),t:Math.round(+c.t),l:c.l==='en'?'en':'ru'}))}catch(e){}}
function chall(){try{return JSON.parse(sessionStorage.getItem(CH)||'null')}catch(e){return null}}
function link(r){return SITE+'?c='+enc({n:nm(r),t:sec(r),l:lng(r)})}
function msg(r){return lng(r)==='en'?`I'm challenging you! 🐾 Help free Pushok. I already did it — you'll see my result only after you finish 😉`:`Бросаю тебе вызов! 🐾 Помоги освободить Пушка. Я уже справился — мой результат ты узнаешь только после игры 😉`}
function share(kind){let r=run();if(!r)return;let u=link(r),t=msg(r),target=kind==='tg'?'https://t.me/share/url?url='+encodeURIComponent(u)+'&text='+encodeURIComponent(t):'https://max.ru/:share?text='+encodeURIComponent(t+'\n'+u);location.href=target}
function visible(el){if(!el)return false;let s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'}
function restart(f){return [...f.querySelectorAll('button,a')].find(x=>/новая игра|сыграть|ещё раз|new game|play again/i.test(x.textContent||''))}
function compare(f){let c=chall(),r=run(),old=q('#pkcmp');if(!c||!r){old?.remove();return}let own=sec(r);if(!own)return;let en=lng(r)==='en',d=c.t-own,res=d>0?(en?`You’re faster by ${d} sec! 🏆`:`Ты быстрее на ${d} сек! 🏆`):d<0?(en?`${-d} sec short. Rematch? 😼`:`Не хватило ${-d} сек. Реванш? 😼`):(en?'Same time! 🤝':'Точное совпадение! 🤝');if(!old){old=document.createElement('div');old.id='pkcmp';old.className='pkcmp'}old.innerHTML=`<h3>${en?'Challenge result unlocked':'Результат вызова открыт'}</h3><div class="pkcmpg"><div class="pkcmpc"><div class="pkcmpn">${en?'You':'Ты'}</div><div class="pkcmpt">${fmt(own)}</div></div><div class="pkcmpc"><div class="pkcmpn"></div><div class="pkcmpt">${fmt(c.t)}</div></div></div><div class="pkcmpr">${res}</div>`;old.querySelectorAll('.pkcmpn')[1].textContent=c.n||'Друг';let sh=q('#pk3');sh?f.insertBefore(old,sh):(restart(f)?.parentNode.insertBefore(old,restart(f))||f.appendChild(old))}
function mount(){let f=q('#finish');if(!f)return;q('#pk-share2')?.remove();q('#pk-share')?.remove();let b=q('#pk3'),r=run(),en=lng(r)==='en';if(!b){b=document.createElement('div');b.id='pk3';b.className='pk3';b.innerHTML=`<h3>${en?'Challenge a friend':'Брось вызов другу'}</h3><p>${en?'Your time stays hidden until your friend finishes.':'Твоё время скрыто — друг увидит его только после своего финиша.'}</p><div class="pk3row"><button class="tg">Telegram</button><button class="mx">MAX</button></div>`;b.querySelector('.tg').onclick=()=>share('tg');b.querySelector('.mx').onclick=()=>share('max');let rbtn=restart(f);rbtn?rbtn.parentNode.insertBefore(b,rbtn):f.appendChild(b)}b.style.display=visible(f)?'block':'none';if(visible(f))compare(f)}
function badge(){let c=chall();if(!c||q('#pkbadge'))return;let b=document.createElement('div');b.id='pkbadge';b.className='pkbadge';b.textContent=c.l==='en'?`🏁 Challenge accepted. Friend's result unlocks after you free Pushok.`:`🏁 Вызов принят. Результат друга откроется только после спасения Пушка.`;(q('.game')||q('.main')||document.body).prepend(b);b.style.display='block'}
ingest();let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);addEventListener('DOMContentLoaded',()=>{badge();mount();setInterval(()=>{badge();mount()},350)});
})();