(()=>{
const A='savekitty_analytics_v1',CH='savekitty_challenge_v1',SITE='https://spasipushka.ru/';
const q=s=>document.querySelector(s);
const css=`.pk4{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff3d3;color:#4a3424}.pk4 h3{margin:0 0 4px;text-align:center;font:950 17px/1.2 system-ui}.pk4 p{margin:0 0 9px;text-align:center;font:750 12px/1.35 system-ui;color:#765c43}.pk4row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pk4 button{border:0;border-radius:12px;min-height:47px;color:#fff;font:900 14px system-ui;touch-action:manipulation}.pk4 .tg{background:#229ed9}.pk4 .mx{background:#111}.pkcmp4{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff8e7;color:#4a3424}.pkcmp4 h3{text-align:center;margin:0 0 9px;font:950 16px system-ui}.pkcmp4g{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pkcmp4c{padding:9px;border:1px solid #ead3a6;border-radius:12px;background:#fffdf8;text-align:center}.pkcmp4n{font:800 11px system-ui;color:#80664c}.pkcmp4t{font:950 24px system-ui;margin-top:3px}.pkcmp4r{margin-top:9px;padding:9px;border-radius:11px;background:#ffd45f;text-align:center;font:950 14px system-ui}.pkbadge4{display:none;margin:8px auto;width:min(520px,calc(100% - 12px));padding:9px 12px;box-sizing:border-box;border:1px solid #d5ad62;border-radius:13px;background:#fff3cf;color:#4b3523;text-align:center;font:850 12px/1.35 system-ui}`;
function rows(){try{return JSON.parse(localStorage.getItem(A)||'[]')||[]}catch(e){return[]}}
function run(){let a=rows();for(let i=a.length-1;i>=0;i--)if(a[i]&&(a[i].completed===true||a[i].event==='completed'))return a[i];return null}
function sec(r){return Math.max(0,Math.round(Number(r?.duration_seconds??r?.duration_sec??r?.elapsed_sec)||0))}
function nm(r){return String(r?.player_name??r?.name??'Игрок').trim().slice(0,40)||'Игрок'}
function lng(r){return (r?.language??r?.lang)==='en'?'en':'ru'}
function fmt(n){n=Math.max(0,Math.round(+n||0));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
const KEY=[83,17,201,44,7,141,62];
function b64u(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';let x=atob(s),a=[];for(let i=0;i<x.length;i++)a.push(x.charCodeAt(i));return a}
function enc(o){try{let raw=new TextEncoder().encode(JSON.stringify(o));let out=[];for(let i=0;i<raw.length;i++)out.push((raw[i]^KEY[i%KEY.length]^((i*29+71)&255))&255);return b64u(out)}catch(e){return''}}
function dec(s){try{let a=unb64u(s),out=[];for(let i=0;i<a.length;i++)out.push((a[i]^KEY[i%KEY.length]^((i*29+71)&255))&255);return JSON.parse(new TextDecoder().decode(new Uint8Array(out)))}catch(e){return null}}
function ingest(){let raw=new URLSearchParams(location.search).get('c');if(!raw)return;let c=dec(raw);if(c&&+c.t>0)try{sessionStorage.setItem(CH,JSON.stringify({n:String(c.n||'Друг').slice(0,40),t:Math.round(+c.t),l:c.l==='en'?'en':'ru'}))}catch(e){}}
function chall(){try{return JSON.parse(sessionStorage.getItem(CH)||'null')}catch(e){return null}}
function link(r){return SITE+'?c='+enc({n:nm(r),t:sec(r),l:lng(r),v:1})}
function msg(r){return lng(r)==='en'?`I'm challenging you! 🐾 Help free Pushok. I already did it — you'll see my result only after you finish 😉`:`Бросаю тебе вызов! 🐾 Помоги освободить Пушка. Я уже справился — мой результат ты узнаешь только после игры 😉`}
function share(kind){let r=run();if(!r)return;let u=link(r),t=msg(r),target=kind==='tg'?'https://t.me/share/url?url='+encodeURIComponent(u)+'&text='+encodeURIComponent(t):'https://max.ru/:share?text='+encodeURIComponent(t+'\n'+u);location.href=target}
function visible(el){if(!el)return false;let s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'}
function restart(f){return [...f.querySelectorAll('button,a')].find(x=>/новая игра|сыграть|ещё раз|new game|play again/i.test(x.textContent||''))}
function compare(f){let c=chall(),r=run(),old=q('#pkcmp4');if(!c||!r){old?.remove();return}let own=sec(r);if(!own)return;let en=lng(r)==='en',d=c.t-own,res=d>0?(en?`You’re faster by ${d} sec! 🏆`:`Ты быстрее на ${d} сек! 🏆`):d<0?(en?`${-d} sec short. Rematch? 😼`:`Не хватило ${-d} сек. Реванш? 😼`):(en?'Same time! 🤝':'Точное совпадение! 🤝');if(!old){old=document.createElement('div');old.id='pkcmp4';old.className='pkcmp4'}old.innerHTML=`<h3>${en?'Challenge result unlocked':'Результат вызова открыт'}</h3><div class="pkcmp4g"><div class="pkcmp4c"><div class="pkcmp4n">${en?'You':'Ты'}</div><div class="pkcmp4t">${fmt(own)}</div></div><div class="pkcmp4c"><div class="pkcmp4n"></div><div class="pkcmp4t">${fmt(c.t)}</div></div></div><div class="pkcmp4r">${res}</div>`;old.querySelectorAll('.pkcmp4n')[1].textContent=c.n||'Друг';let sh=q('#pk4');sh?f.insertBefore(old,sh):(restart(f)?.parentNode.insertBefore(old,restart(f))||f.appendChild(old))}
function mount(){let f=q('#finish');if(!f)return;q('#pk-share2')?.remove();q('#pk-share')?.remove();q('#pk3')?.remove();q('#pkcmp')?.remove();let b=q('#pk4'),r=run(),en=lng(r)==='en';if(!b){b=document.createElement('div');b.id='pk4';b.className='pk4';b.innerHTML=`<h3>${en?'Challenge a friend':'Брось вызов другу'}</h3><p>${en?'Your time stays hidden until your friend finishes.':'Твоё время скрыто — друг увидит его только после своего финиша.'}</p><div class="pk4row"><button class="tg">Telegram</button><button class="mx">MAX</button></div>`;b.querySelector('.tg').onclick=()=>share('tg');b.querySelector('.mx').onclick=()=>share('max');let rbtn=restart(f);rbtn?rbtn.parentNode.insertBefore(b,rbtn):f.appendChild(b)}b.style.display=visible(f)?'block':'none';if(visible(f))compare(f)}
function badge(){let c=chall();if(!c||q('#pkbadge4'))return;let b=document.createElement('div');b.id='pkbadge4';b.className='pkbadge4';b.textContent=c.l==='en'?`🏁 Challenge accepted. Friend's result unlocks after you free Pushok.`:`🏁 Вызов принят. Результат друга откроется только после спасения Пушка.`;(q('.game')||q('.main')||document.body).prepend(b);b.style.display='block'}
ingest();let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);addEventListener('DOMContentLoaded',()=>{badge();mount();setInterval(()=>{badge();mount()},350)});
})();