(()=>{
const A='savekitty_analytics_v1',CH='savekitty_challenge_v3',SITE='https://spasipushka.ru/',API='https://spasipushka-api.kutuzovap.workers.dev',K=[31,117,9,203,44],CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const q=s=>document.querySelector(s);let prepared=null,preparing=false,revealed='';
const css=`.pk6,.pkcmp6{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff3d3;color:#4a3424}.pk6 h3,.pkcmp6 h3{margin:0 0 5px;text-align:center;font:950 17px/1.2 system-ui}.pk6 p{margin:0 0 9px;text-align:center;font:750 12px/1.35 system-ui;color:#765c43}.pk6row,.pkcmp6share{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pk6 button,.pkcmp6share button{border:0;border-radius:12px;min-height:47px;color:#fff;font:900 14px system-ui;touch-action:manipulation}.tg{background:#229ed9}.mx{background:#111}.pkcmp6{background:#fff8e7}.pkcmp6g{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pkcmp6c{padding:10px;border:1px solid #ead3a6;border-radius:12px;background:#fffdf8;text-align:center}.pkcmp6n{font:800 11px system-ui;color:#80664c}.pkcmp6t{font:950 25px system-ui;margin-top:3px}.pkcmp6r{margin:9px 0;padding:10px;border-radius:11px;background:#ffd45f;text-align:center;font:950 14px system-ui}.pkcmp6cap{text-align:center;color:#80664c;font:800 11px system-ui;margin:3px 0 7px}.pkbadge6{display:none;margin:8px auto;width:min(520px,calc(100% - 12px));padding:9px 12px;box-sizing:border-box;border:1px solid #d5ad62;border-radius:13px;background:#fff3cf;color:#4b3523;text-align:center;font:850 12px/1.35 system-ui}`;
function rows(){try{return JSON.parse(localStorage.getItem(A)||'[]')||[]}catch{return[]}}function run(){let a=rows();for(let i=a.length-1;i>=0;i--)if(a[i]&&(a[i].completed===true||a[i].event==='completed'))return a[i];return null}function sec(r){return Math.max(0,Math.round(Number(r?.duration_seconds??r?.duration_sec??r?.elapsed_sec)||0))}function nm(r){return String(r?.player_name??r?.name??localStorage.getItem('savekitty_player_name_v1')??'Игрок').trim().slice(0,40)||'Игрок'}function lng(r){return (r?.language??r?.lang)==='en'?'en':'ru'}function fmt(n){n=Math.max(0,Math.round(+n||0));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}function pid(){try{return localStorage.getItem('savekitty_player_id')||''}catch{return''}}function visible(el){if(!el)return false;let s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'}function restart(f){return [...f.querySelectorAll('button,a')].find(x=>/новая игра|сыграть|ещё раз|new game|play again/i.test(x.textContent||''))}function rid(){let s='';const b=new Uint8Array(6);crypto.getRandomValues(b);for(const x of b)s+=CHARS[x%CHARS.length];return s}
function enc(o){try{const a=new TextEncoder().encode(JSON.stringify(o)),b=[];for(let i=0;i<a.length;i++)b.push(a[i]^K[i%K.length]^((i*17+23)&255));let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}catch{return''}}function dec(s){try{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const x=atob(s),b=[];for(let i=0;i<x.length;i++)b.push(x.charCodeAt(i)^K[i%K.length]^((i*17+23)&255));return JSON.parse(new TextDecoder().decode(new Uint8Array(b)))}catch{return null}}
function store(c){try{sessionStorage.setItem(CH,JSON.stringify(c))}catch{}}function chall(){try{return JSON.parse(sessionStorage.getItem(CH)||'null')}catch{return null}}function challengeId(){const raw=new URLSearchParams(location.search).get('c')||'';return /^[A-HJ-NP-Z2-9]{6}$/i.test(raw)?raw.toUpperCase():''}function fallbackHash(){const m=location.hash.match(/(?:^#|&)r=([^&]+)/);return m?dec(m[1]):null}
async function ingest(){const id=challengeId();if(!id)return;const fb=fallbackHash();let c={id,n:String(fb?.n||'Друг').slice(0,40),l:fb?.l==='en'?'en':'ru',t:Number(fb?.t)||0};store(c);badge();try{const r=await fetch(API+'/challenge/'+id,{cache:'no-store'});if(r.ok){const j=await r.json();c={...c,n:String(j.challenge?.inviter_name||c.n).slice(0,40),l:j.challenge?.language==='en'?'en':c.l};store(c);badge()}}catch{}}
function inviteMsg(r){return lng(r)==='en'?`I'm challenging you! 🐾 Help free Pushok. I already did it — you'll see my result only after you finish 😉`:`Бросаю тебе вызов! 🐾 Помоги освободить Пушка. Я уже справился — мой результат ты узнаешь только после игры 😉`}
function fallbackLink(r,id=rid()){const token=enc({n:nm(r),t:sec(r),l:lng(r)});return{id,url:SITE+'?c='+id+'#r='+token}}
function prime(){const r=run();if(!r||prepared||preparing)return;prepared=fallbackLink(r);preparing=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);fetch(API+'/challenge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:pid(),player_name:nm(r),language:lng(r)}),signal:controller.signal}).then(async res=>{if(res.ok){const j=await res.json();if(j?.challenge?.id)prepared=fallbackLink(r,j.challenge.id)}}).catch(()=>{}).finally(()=>{clearTimeout(timer);preparing=false})}
function share(kind){const r=run();if(!r)return;prime();const p=prepared||fallbackLink(r),t=inviteMsg(r);const target=kind==='tg'?'https://t.me/share/url?url='+encodeURIComponent(p.url)+'&text='+encodeURIComponent(t):'https://max.ru/:share?text='+encodeURIComponent(t+'\n'+p.url);location.href=target}
function comparisonText(x,en){const own=Number(x.recipient_duration_seconds)||0,theirs=Number(x.inviter_duration_seconds)||0,d=theirs-own,name=x.inviter_name||'Друг';if(en)return `I finished the Pushok challenge! 🐾\nMe — ${fmt(own)} | ${name} — ${fmt(theirs)}\n${d>0?`I was faster by ${d} sec! 🏆`:d<0?`${name} was faster by ${-d} sec 😼`:'Same time! 🤝'}\n${SITE}`;return `Я прошёл вызов «Спаси Пушка»! 🐾\nЯ — ${fmt(own)} | ${name} — ${fmt(theirs)}\n${d>0?`Я быстрее на ${d} сек! 🏆`:d<0?`${name} быстрее на ${-d} сек 😼`:'Точное совпадение! 🤝'}\n${SITE}`}
function shareComparison(kind,x,en){const t=comparisonText(x,en),u=kind==='tg'?'https://t.me/share/url?url='+encodeURIComponent(SITE)+'&text='+encodeURIComponent(t):'https://max.ru/:share?text='+encodeURIComponent(t);location.href=u}
function renderComparison(f,x,r,c){const own=Number(x.recipient_duration_seconds)||sec(r),theirs=Number(x.inviter_duration_seconds)||Number(c.t)||0;if(!theirs)return;const en=lng(r)==='en',d=theirs-own,name=x.inviter_name||c.n||'Друг',result=d>0?(en?`You’re faster by ${d} sec! 🏆`:`Ты быстрее на ${d} сек! 🏆`):d<0?(en?`${name} is faster by ${-d} sec 😼`:`${name} быстрее на ${-d} сек 😼`):(en?'Same time! 🤝':'Точное совпадение! 🤝');let box=q('#pkcmp6');if(!box){box=document.createElement('div');box.id='pkcmp6';box.className='pkcmp6'}box.innerHTML=`<h3>${en?'Challenge result unlocked':'Результат вызова открыт'}</h3><div class="pkcmp6g"><div class="pkcmp6c"><div class="pkcmp6n">${en?'You':'Ты'}</div><div class="pkcmp6t">${fmt(own)}</div></div><div class="pkcmp6c"><div class="pkcmp6n"></div><div class="pkcmp6t">${fmt(theirs)}</div></div></div><div class="pkcmp6r">${result}</div><div class="pkcmp6cap">${en?'Send the result back':'Отправь сравнение тому, кто тебя вызвал'}</div><div class="pkcmp6share"><button class="tg">Telegram</button><button class="mx">MAX</button></div>`;box.querySelectorAll('.pkcmp6n')[1].textContent=name;const payload={...x,inviter_name:name,inviter_duration_seconds:theirs,recipient_duration_seconds:own};box.querySelector('.tg').onclick=()=>shareComparison('tg',payload,en);box.querySelector('.mx').onclick=()=>shareComparison('max',payload,en);const sh=q('#pk6');sh?f.insertBefore(box,sh):(restart(f)?.parentNode.insertBefore(box,restart(f))||f.appendChild(box));revealed=c.id}
async function compare(f){const c=chall(),r=run();if(!c?.id||!r||revealed===c.id)return;if(c.t>0)renderComparison(f,{inviter_name:c.n,inviter_duration_seconds:c.t,recipient_duration_seconds:sec(r)},r,c);try{const res=await fetch(API+'/challenge/'+c.id+'/reveal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:pid(),recipient_duration_seconds:sec(r),completed_at:r.completed_at||new Date().toISOString()})});if(res.ok){const j=await res.json();if(j?.result)renderComparison(f,j.result,r,c)}}catch{}}
function mount(){const f=q('#finish');if(!f)return;['#pk5','#pkcmp5','#pk4','#pkcmp4','#pk-share','#pk-share2'].forEach(s=>q(s)?.remove());const r=run(),en=lng(r)==='en';let b=q('#pk6');if(!b){b=document.createElement('div');b.id='pk6';b.className='pk6';b.innerHTML=`<h3>${en?'Challenge a friend':'Брось вызов другу'}</h3><p>${en?'Your time stays hidden until your friend finishes.':'Твоё время скрыто — друг увидит его только после своего финиша.'}</p><div class="pk6row"><button class="tg">Telegram</button><button class="mx">MAX</button></div>`;b.querySelector('.tg').onclick=()=>share('tg');b.querySelector('.mx').onclick=()=>share('max');let rb=restart(f);rb?rb.parentNode.insertBefore(b,rb):f.appendChild(b)}b.style.display=visible(f)?'block':'none';if(visible(f)){prime();compare(f)}}
function badge(){const c=chall();let b=q('#pkbadge6');if(!c?.id)return;if(!b){b=document.createElement('div');b.id='pkbadge6';b.className='pkbadge6';(q('.game')||q('.main')||document.body).prepend(b)}const en=c.l==='en';b.textContent=en?`🏁 Challenge from ${c.n||'a friend'} accepted. Their result unlocks after you free Pushok.`:`🏁 Вызов от ${c.n||'друга'} принят. Результат откроется только после спасения Пушка.`;b.style.display='block'}
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);addEventListener('DOMContentLoaded',()=>{ingest();badge();mount();setInterval(()=>{badge();mount()},700)});
})();