(()=>{
const A='savekitty_analytics_v1',CH='savekitty_challenge_v2',SITE='https://spasipushka.ru/',API='https://spasipushka-api.kutuzovap.workers.dev';
const q=s=>document.querySelector(s);
const css=`.pk5{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff3d3;color:#4a3424}.pk5 h3{margin:0 0 4px;text-align:center;font:950 17px/1.2 system-ui}.pk5 p{margin:0 0 9px;text-align:center;font:750 12px/1.35 system-ui;color:#765c43}.pk5row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pk5 button{border:0;border-radius:12px;min-height:47px;color:#fff;font:900 14px system-ui;touch-action:manipulation}.pk5 button:disabled{opacity:.65}.pk5 .tg{background:#229ed9}.pk5 .mx{background:#111}.pkcmp5{width:min(540px,calc(100% - 8px));margin:10px auto;padding:12px;box-sizing:border-box;border:1px solid #d9b66f;border-radius:17px;background:#fff8e7;color:#4a3424}.pkcmp5 h3{text-align:center;margin:0 0 9px;font:950 16px system-ui}.pkcmp5g{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pkcmp5c{padding:9px;border:1px solid #ead3a6;border-radius:12px;background:#fffdf8;text-align:center}.pkcmp5n{font:800 11px system-ui;color:#80664c}.pkcmp5t{font:950 24px system-ui;margin-top:3px}.pkcmp5r{margin-top:9px;padding:9px;border-radius:11px;background:#ffd45f;text-align:center;font:950 14px system-ui}.pkbadge5{display:none;margin:8px auto;width:min(520px,calc(100% - 12px));padding:9px 12px;box-sizing:border-box;border:1px solid #d5ad62;border-radius:13px;background:#fff3cf;color:#4b3523;text-align:center;font:850 12px/1.35 system-ui}`;
function rows(){try{return JSON.parse(localStorage.getItem(A)||'[]')||[]}catch(e){return[]}}
function run(){let a=rows();for(let i=a.length-1;i>=0;i--)if(a[i]&&(a[i].completed===true||a[i].event==='completed'))return a[i];return null}
function sec(r){return Math.max(0,Math.round(Number(r?.duration_seconds??r?.duration_sec??r?.elapsed_sec)||0))}
function nm(r){return String(r?.player_name??r?.name??localStorage.getItem('savekitty_player_name_v1')??'Игрок').trim().slice(0,40)||'Игрок'}
function lng(r){return (r?.language??r?.lang)==='en'?'en':'ru'}
function fmt(n){n=Math.max(0,Math.round(+n||0));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
function playerId(){try{return localStorage.getItem('savekitty_player_id')||''}catch(e){return''}}
function visible(el){if(!el)return false;let s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'}
function restart(f){return [...f.querySelectorAll('button,a')].find(x=>/новая игра|сыграть|ещё раз|new game|play again/i.test(x.textContent||''))}
function storeChallenge(c){try{sessionStorage.setItem(CH,JSON.stringify(c))}catch(e){}}
function chall(){try{return JSON.parse(sessionStorage.getItem(CH)||'null')}catch(e){return null}}
function challengeId(){const raw=new URLSearchParams(location.search).get('c')||'';return /^[A-HJ-NP-Z2-9]{6}$/i.test(raw)?raw.toUpperCase():''}
async function ingest(){const id=challengeId();if(!id)return;let c={id,n:'Друг',l:'ru'};storeChallenge(c);try{const r=await fetch(API+'/challenge/'+id,{cache:'no-store'});if(r.ok){const j=await r.json();c={id,n:String(j.challenge?.inviter_name||'Друг').slice(0,40),l:j.challenge?.language==='en'?'en':'ru'};storeChallenge(c);badge(true)}}catch(e){}}
function msg(r){return lng(r)==='en'?`I'm challenging you! 🐾 Help free Pushok. I already did it — you'll see my result only after you finish 😉`:`Бросаю тебе вызов! 🐾 Помоги освободить Пушка. Я уже справился — мой результат ты узнаешь только после игры 😉`}
async function createChallenge(r){const pid=playerId();if(!pid)throw new Error('player id missing');try{await window.saveKittySupabaseSync?.()}catch(e){};for(let i=0;i<4;i++){const res=await fetch(API+'/challenge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:pid,player_name:nm(r),language:lng(r)})});if(res.ok){const j=await res.json();return j.challenge.id}if(res.status!==409)throw new Error('challenge '+res.status);await new Promise(x=>setTimeout(x,500+300*i));try{await window.saveKittySupabaseSync?.()}catch(e){}}throw new Error('result still syncing')}
async function share(kind,btn){let r=run();if(!r)return;const old=btn.textContent;btn.disabled=true;btn.textContent=lng(r)==='en'?'Creating…':'Создаю…';try{const id=await createChallenge(r),u=SITE+'?c='+id,t=msg(r),target=kind==='tg'?'https://t.me/share/url?url='+encodeURIComponent(u)+'&text='+encodeURIComponent(t):'https://max.ru/:share?text='+encodeURIComponent(t+'\n'+u);location.href=target}catch(e){btn.textContent=lng(r)==='en'?'Try again':'Повторить';setTimeout(()=>{btn.disabled=false;btn.textContent=old},1400);return}btn.disabled=false;btn.textContent=old}
let revealBusy=false,revealed='';
async function compare(f){let c=chall(),r=run(),old=q('#pkcmp5');if(!c?.id||!r){old?.remove();return}if(revealed===c.id)return;if(revealBusy)return;revealBusy=true;try{const res=await fetch(API+'/challenge/'+c.id+'/reveal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:playerId()})});if(!res.ok)return;const j=await res.json(),x=j.result;if(!x)return;const own=Number(x.recipient_duration_seconds)||sec(r),theirs=Number(x.inviter_duration_seconds)||0,en=lng(r)==='en',d=theirs-own,result=d>0?(en?`You’re faster by ${d} sec! 🏆`:`Ты быстрее на ${d} сек! 🏆`):d<0?(en?`${-d} sec short. Rematch? 😼`:`Не хватило ${-d} сек. Реванш? 😼`):(en?'Same time! 🤝':'Точное совпадение! 🤝');if(!old){old=document.createElement('div');old.id='pkcmp5';old.className='pkcmp5'}old.innerHTML=`<h3>${en?'Challenge result unlocked':'Результат вызова открыт'}</h3><div class="pkcmp5g"><div class="pkcmp5c"><div class="pkcmp5n">${en?'You':'Ты'}</div><div class="pkcmp5t">${fmt(own)}</div></div><div class="pkcmp5c"><div class="pkcmp5n"></div><div class="pkcmp5t">${fmt(theirs)}</div></div></div><div class="pkcmp5r">${result}</div>`;old.querySelectorAll('.pkcmp5n')[1].textContent=x.inviter_name||c.n||'Друг';let sh=q('#pk5');sh?f.insertBefore(old,sh):(restart(f)?.parentNode.insertBefore(old,restart(f))||f.appendChild(old));revealed=c.id}catch(e){}finally{revealBusy=false}}
function mount(){let f=q('#finish');if(!f)return;['#pk-share2','#pk-share','#pk3','#pk4','#pkcmp','#pkcmp4'].forEach(s=>q(s)?.remove());let b=q('#pk5'),r=run(),en=lng(r)==='en';if(!b){b=document.createElement('div');b.id='pk5';b.className='pk5';b.innerHTML=`<h3>${en?'Challenge a friend':'Брось вызов другу'}</h3><p>${en?'Your time stays hidden until your friend finishes.':'Твоё время скрыто — друг увидит его только после своего финиша.'}</p><div class="pk5row"><button class="tg">Telegram</button><button class="mx">MAX</button></div>`;b.querySelector('.tg').onclick=e=>share('tg',e.currentTarget);b.querySelector('.mx').onclick=e=>share('max',e.currentTarget);let rb=restart(f);rb?rb.parentNode.insertBefore(b,rb):f.appendChild(b)}b.style.display=visible(f)?'block':'none';if(visible(f))compare(f)}
function badge(refresh=false){let c=chall(),b=q('#pkbadge5');if(!c?.id)return;if(!b){b=document.createElement('div');b.id='pkbadge5';b.className='pkbadge5';(q('.game')||q('.main')||document.body).prepend(b)}const en=c.l==='en';b.textContent=en?`🏁 Challenge from ${c.n||'a friend'} accepted. Their result unlocks after you free Pushok.`:`🏁 Вызов от ${c.n||'друга'} принят. Результат откроется только после спасения Пушка.`;b.style.display='block'}
let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);addEventListener('DOMContentLoaded',()=>{ingest();badge();mount();setInterval(()=>{badge();mount()},700)});
})();